/** Declaration file generated by dts-gen */

export function levenshtein(stringA: any, stringB: any, insertCb: any, removeCb: any, updateCb: any): any;

export function ted(rootA: any, rootB: any, childrenCb: any, insertCb: any, removeCb: any, updateCb: any): any;

